# 吸尘箱控制
std_msgs/Header  header

uint8 engin_start            #一键启动
uint8 side_brush             #边刷启动
uint8 main_brush             #主刷启动
uint8 spray_motor            #喷水电机
uint8 dust_suppresion        #振尘电机
int8  lift_motor             #边刷升降
uint8 led                    #led灯
uint8 control_mode           #控制模式 
uint8 dustbin_on_car         #箱子在车上的标志位
uint8 auto_push               #自动倾倒
uint8 fan_speed              #风机速度
uint8 unused0                #预留位0
uint8 unused1                #预留位1

