# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
stages:
  - deploy
image: 192.168.12.16:5000/sunny-ctirobot/cti_ade_base_foxy:latest
.tags: &tag
  - foxy

deploy:
  tags:
    - foxy
  stage: deploy
  script:
    - rosdep update
    - sed -i 's/my $ignore_missing_info = 0;/my $ignore_missing_info = 1;/g' /usr/bin/dpkg-shlibdeps
    - bash .make_deb.sh
    - mv ../*.deb . && mv ../*.ddeb .
    - bash .upload.sh
  artifacts:
    paths:
      - "*.deb"
    expire_in: 1 week